Add SnapConfig.unset
albertodonato/snap-helpers pull request #9
Opened 2023-01-09 12:39 UTC by gnuoy

Add SnapConfig.unset
    
Add SnapConfig.unset to allow for config keys to be unset via the
SnapConfig object.

2023-01-09 15:25 UTC, sparkiegeek requested changes
Don't think you want the .snap added to the repo?

2023-01-09 15:25 UTC, sparkiegeek commented on integration_tests.py
> +        pass
use `contextlib.suppress` for ease of reading?

```suggestion
    with suppress(UnknownConfigKey):
        snap.config.unset(['foo', 'goo'])
```

2023-01-09 20:27 UTC, albertodonato requested changes
Thanks for the changes! 

Just a couple of nits inline.

Also please run `tox -e format` to ensure formatting, and a unit test for `unset` in `snaphelpers/tests/test_conf.py` (similar to the one for `set`) would also be needed.

2023-01-09 20:27 UTC, albertodonato commented on integration_tests.py
> +    with contextlib.suppress(UnknownConfigKey):
this shouldn't be needed, since unset won't fail if the config doesn't exist

2023-01-09 20:27 UTC, albertodonato commented on integration_tests.py
> +    # Start Test:
this comment could be dropped

2023-01-11 12:54 UTC, albertodonato approved these changes
Thanks for fixing CI issues!

I'll take a look at running integration tests as root separately, so that's possible to add tests like the one you had.

2023-01-11 12:54 UTC, merged